### ISSUE TITLE
Update on SDK readiness?

### ISSUE THREAD

**Issue by mpicco** [openpeer/opandroid#251]
Hi Guys, 

From the looks of the issues list it appears that the SDK still isn't ready yet.  I was able to build it and run it to the point of requesting Facebook authorization, but then it hangs.

I've successfully used the iOS version and am anxious to get going on Android because I would like to use it with a Glass app.  (Actually there's a hackathon this weekend that I had hoped to use it for, but that's probably unrealistic.)

Anyway, would it be possible for you to comment on the readiness of the android port?  I  would be happy to help test if that would be useful.

Thanks,

Marty

**Comment by elagerway** [comment]
Marty, android is now available and relatively stable.

https://github.com/openpeer/opandroid
