### ISSUE TITLE
Call setup/answering/hungup very slow

### ISSUE THREAD

**Issue by brucexia** [openpeer/opandroid#722]
Logs:
david gofour: http://io-devcomp-portal.hcs-stack-admin-idc5ef34-0.vm.hcs.io:8013/#/logs/incoming/108.172.40.3~4ce27fb8d7350697-8f052f52-6246-4fdd-bbb7-37da5a91fec7

david go3 http://io-devcomp-portal.hcs-stack-admin-idc5ef34-0.vm.hcs.io:8013/#/logs/incoming/108.172.40.3~795b33f8d7b6b16-61e02a67-f9a9-434c-8987-f95c99dbe884

david gofour  started app
david gothree started app
four sent message "test1" to three
test1 arrived on three instantly
3 sent "3test1" to 4
4 sent "4test2" to 3
messaging two are pretty decent so far
4 then placed a call to 3
the call took more than 10 seconds to pop up on 3, then 3 answered, 4 didn't receive answer for over 50 seconds, then 3 hungup, right after 3 hungup 4 received answer, then hungup after a few secons

brucexia [9:33 AM]
Now I'm going to make a second call from 4 to 3

brucexia [9:34 AM]
This time the call setup time is same, over 10 seconds, but answer is received instantly,but hungup from 3 took couple seconds to be received by 4. Lookat call around 17:33

brucexia [9:35 AM]
now I'm going to test couple more messaging then quit the app so the log doesn't grow too big

brucexia [9:36 AM]
messaging okay so far

**Comment by robin-raymond** [comment]
@morosev I'm seeing lots of media related errors. Could the be the reason? Maybe they are errors but none critical. I can't tell.

**Comment by brucexia0** [comment]
closing for now since i cannot reproduce when logger is off.

**Comment by brucexia** [comment]
closing this for now since i cannot reproduce when logger is off
